limit_dataset:
- ling-spam
- ng20
#- nyt_200
- r8
- review_polarity
- rotten_imdb
- tagmynews
#- ted_talks
limit_graph_type:
- concept_map
params_per_type:
  graph:
    feature_extraction:
      fast_wl:
        h:
        - 10
        node_weight_function:
        - ~
        same_label:
        - false
      phi_picker:
        return_iteration:
        - stacked
        use_zeroth:
        - false
        - true
    graph_preprocessing:
      VAL_:
      - RemoveInfrequentGraphLabels
      max_occurrences:
      - 1
      - 2
      - 3
    normalizer:
    - MaxAbsScaler