limit_dataset:
- ling-spam
- ng20
limit_graph_type:
- concept_map
params_per_type:
  graph:
    feature_extraction:
      fast_wl:
        h:
        - 10
        node_weight_function:
        - ~
        round_to_decimals:
        - 10
        same_label:
        - false
      phi_picker:
        return_iteration:
        - stacked
        use_zeroth:
        - false
        - true
    graph_preprocessing:
    - ~
    - RemoveSingleOccurrenceGraphLabels
    normalizer:
    - MaxAbsScaler