limit_dataset:
#- ling-spam
- ng20
#- reuters-21578
- review_polarity
- rotten_imdb
- ted_talks
#- tagmynews
#- webkb
limit_graph_type:
- concept_map
params_per_type:
  graph:
    feature_extraction:
      fast_wl:
        h:
        - 10
        node_weight_function:
        - ~
        round_to_decimals:
        - 10
      phi_picker:
        return_iteration:
        - stacked
        use_zeroth:
        - True
        - False
    graph_preprocessing: ~
    normalizer:
    - MaxAbsScaler