limit_dataset:
- ng20
limit_graph_type:
- concept_map
- cooccurrence
params_per_type:
  text:
    classifier:
      C:
      - 0.001
      - 0.01
      - 1
    preprocessing:
    - SimplePreProcessingTransformer
    scaler:
    - MaxAbsScaler
    vectorizer:
      VAL_:
      #- CountVectorizer
      - TfidfVectorizer
      binary:
      - true
      #- false
      ngram_range:
      - !!python/tuple
        - 1
        - 1
  graph_combined:
    classifier:
      C:
      - 0.001
      - 0.01
      - 1
    features:
      fast_wl_pipeline:
        feature_extraction:
          feature_extraction:
            fast_wl:
              h:
              - 10
              node_weight_function:
              - ~
              round_to_decimals:
              - 10
            phi_picker:
              return_iteration:
              - stacked
              use_zeroth:
              - false
          normalizer:
          - MaxAbsScaler
      text:
        vectorizer:
          preprocessing:
          - SimplePreProcessingTransformer
          scaler:
          - MaxAbsScaler
          vectorizer:
            VAL_:
            #- CountVectorizer
            - TfidfVectorizer
            binary:
            - true
            #- false
            ngram_range:
            - !!python/tuple
              - 1
              - 1