limit_graph_type:
- concept_map
params_per_type:
  graph_relabeled:
    feature_extraction:
      fast_wl:
        h:
        - 10
        ignore_label_order:
        - false
        node_weight_function:
        - ~
        round_to_decimals:
        - 10
        same_label:
        - false
        use_directed:
        - true
        use_early_stopping:
        - false
      phi_picker:
        return_iteration:
        - stacked
        use_zeroth:
        - false
        - true
    graph_preprocessing:
      VAL_:
      - RelabelGraphsTransformer
      threshold:
      - 0.5
      - 0.7
      - 0.9
      - 0.99
      topn:
      #- 1
      #- 2
      #- 5
      - 10
    normalizer:
    - ~ #MaxAbsScaler