params_per_type:
  dummy_most_frequent:
    classifier:
      C: null
      VAL_:
      - DummyClassifier
      class_weight: null
      max_iter: null
      strategy:
      - uniform
      tol: null
  dummy_stratified:
    classifier:
      C: null
      VAL_:
      - DummyClassifier
      class_weight: null
      max_iter: null
      strategy:
      - uniform
      tol: null
  dummy_uniform:
    classifier:
      C: null
      VAL_:
      - DummyClassifier
      class_weight: null
      max_iter: null
      strategy:
      - uniform
      tol: null