limit_dataset:
- ling-spam
- ng20
- ted_talks
- nyt_small
- nyt_middle
- nyt_200
- review_polarity
- r8
limit_graph_type:
- concept_map
params_per_type:
  graph_combined:
    classifier:
      C:
      - 0.001
      - 0.01
      #- 0.1
      - 1
    features:
      fast_wl_pipeline:
        feature_extraction:
          feature_extraction:
            fast_wl:
              h:
              - 10
              node_weight_function:
              - ~
              round_to_decimals:
              - 10
              same_label:
              - true
            phi_picker:
              return_iteration:
              - stacked
              use_zeroth:
              - false
              - true
          normalizer:
          - MaxAbsScaler
      text:
        vectorizer:
          preprocessing:
          - SimplePreProcessingTransformer
          scaler:
          - MaxAbsScaler
          vectorizer:
            VAL_:
            - CountVectorizer
            - TfidfVectorizer
            binary:
            - true
            - false
            ngram_range:
            - !!python/tuple
              - 1
              - 1