limit_graph_type:
- concept_map
params_per_type:
  graph:
    feature_extraction:
      fast_wl:
        h:
        - 6
        ignore_label_order:
        - false
        node_weight_function:
        - ~
        round_to_decimals:
        - 10
        same_label:
        - false
        use_directed:
        - true
        use_early_stopping:
        - true
        - false
      phi_picker:
        return_iteration:
        - stacked
        use_zeroth:
        - true
    graph_preprocessing:
    - ~
    normalizer:
    - MaxAbsScaler