experiment_name: 'just_a_test'
limit_dataset:
- ling-spam
params_per_type:
  text:
    preprocessing:
    - SimplePreProcessingTransformer
    scaler:
    - MaxAbsScaler
    vectorizer:
      VAL_:
      - TfidfVectorizer
      binary:
      - true
